== Delmonico Steak

Generally when choosing steaks, my go-to is the Delmonico steak of a 1/2" thickness.  It has a good fat content and cooks well both indoors in an oven under the broiler or on the grill or smoker.  I can rarely find bone-in Delmonicos but they're by far my favorite when I stumble across them. 

To prepare the steak, generally speaking I do not rinse it off.  Dry off both sides of the steak with a paper towel and discard the towel.  Trim excess fat off the delmonico if you desire but I do not.  I find the extra fat helps to keep the steak moist during cooking.  Season both sides liberally with kosher salt, pepper and garlic powder prior to cooking.  

=== Grilling

TODO

=== Broiling

Broiling is essentially grilling upside down, so my broiling method is informed upon my experiments with the grill.  

Arrange steaks so they are not touching on a broiling pan.  Move your top oven rack to the top, or second position from the top.  Set the broiler for its low setting.  You will need to experiment a little as every oven is different.  I broil on my the first side for 6 minutes, flip the steaks once and cook on the second side for 3 minutes.  When complete, the steaks should be well browned on both sides.  A thermometer placed laterally along the steak should measure between 115 and 120 degrees Ferenheit.  If its underdone, put in back into the broiler for a minute, thirty seconds, take out a steak and test it again.  Once complete, place the steaks in a single layer on a plate and tent with aluminum foil.  